version: "3"
services:
   database:
      image: postgres:9.6
      container_name: "postgres"
      environment:
         - POSTGRES_DB=mrm
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=user
         - TZ=GMT
      volumes:
         - "./data/postgres:/var/lib/postgresql/data"
      ports:
         - 5432:5432